# https://github.com/helix-editor/helix/blob/master/.github/workflows/release.yml
name: Release

on:
  pull_request:
    branches:
      - "releases/**"
    paths:
      - ".github/workflows/release.yml"
  push:
    branches:
      - "releases/**"
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

env:
  # Preview mode: Publishes the build output as a CI artifact instead of creating
  # a release, allowing for manual inspection of the output. This mode is
  # activated if the CI run was triggered by events other than pushed tags, or
  # if the repository is a fork.
  preview: ${{ !startsWith(github.ref, 'refs/tags/') || github.repository != 'LEI/pullr' }}

jobs:
  publish:
    name: Publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pullr
            asset_name: pullr-linux-amd64
          - os: macos-latest
            artifact_name: pullr
            asset_name: pullr-macos-amd64
          - os: windows-latest
            artifact_name: pullr.exe
            asset_name: pullr-windows-amd64
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo build
        run: cargo build --release --locked

      # https://github.com/actions/upload-artifact
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v3
        if: env.preview == 'true'
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.artifact_name }}

      # https://github.com/svenstaro/upload-release-action
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: env.preview == 'false'
        with:
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          overwrite: true
